version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node-red
    versions:
    - 1.2.8
    - 1.2.9
    - 1.3.1
    - 1.3.2
  - dependency-name: querystring
    versions:
    - 0.2.1
  - dependency-name: node-red-node-test-helper
    versions:
    - 0.2.6
    - 0.2.7
  - dependency-name: mocha
    versions:
    - 8.3.0
